routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\Auth\ResetPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('/home');
});

// Роуты Laravel UI
Auth::routes();
// Редирект роута регистрации
Route::get('/register', function () {
    return redirect('/login');
});
// Предоставление доступа
Route::get('/password/fill/{token}', 'Auth\ResetPasswordController@fill')->name('password.fill');
Route::post('/password/fill/{token}', 'Auth\ResetPasswordController@fillPost')->name('password.fill.post');




Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');
Route::get('/certificate/{hash}', 'HomeController@certificate')->name('certificate');
Route::get('/centificate/{hash}', function ($hash) {
    return redirect('/certificate/'.$hash);
});

Route::group(['middleware' => ['auth']], function() {
    // API
    include('webapi.php');
    
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController', [ 'names' => 'users' ])->middleware('permission:user-edit');;
    Route::get('/users/{user}/auth', 'UserController@auth');

    Route::resource('meetings', 'MeetingController');
    Route::resource('subdivisions', 'SubdividionController');
    Route::resource('groups', 'GroupController');

    // Отвязывание роли
    Route::delete('users/{user}/detachRole/{role}', 'UserController@detachRole')->where('user', '[0-9]+')->where('role', '[0-9]+');
    // Привязка роли
    Route::post('users/{user}/attachRole/{role}', 'UserController@attachRole')->where('user', '[0-9]+')->where('role', '[0-9]+');

    // Настройки
    Route::get('/profile', 'UserController@profile')->name('profile');

    Route::get('/meetings/{meeting}/students', 'MeetingController@students')->name('meetings.students');
    Route::post('/meetings/{meeting}/students', 'MeetingController@postStudents')->middleware('permission:meeting-create');

    Route::get('/meetings/{meeting}/report/{user}', 'MeetingController@report')->name('meetings.report');
    Route::post('/meetings/{meeting}/report/{user}', 'MeetingController@postReport');
    Route::get('/meetings/{meeting}/report/{user}/download', 'MeetingController@downloadReport');

    Route::get('/meetings/{meeting}/exam/{user}', 'MeetingController@exam')->name('meetings.exam');
    Route::post('/meetings/{meeting}/exam/{user}', 'MeetingController@postExam');
    Route::get('/meetings/{meeting}/exam/{user}/download', 'MeetingController@downloadExam');

    Route::get('/meetings/{meeting}/exam/{examProtocol}/votes', 'MeetingController@examVotes');
    Route::get('/meetings/{meeting}/report/{reportProtocol}/votes', 'MeetingController@reportVotes');

    Route::get('/meetings/{meeting}/solution/{user}', 'MeetingController@solution')->name('meetings.solution');
    Route::post('/meetings/{meeting}/solution/{user}', 'MeetingController@postSolution');
    Route::get('/meetings/{meeting}/solution/{user}/download', 'MeetingController@downloadSolution');

    Route::get('/meetings/{meeting}/confirm', 'MeetingController@confirm')->name('meetings.confirm');

    Route::get('/meetings/{meeting}/tickets', 'MeetingController@tickets')->name('meetings.tickets');
    Route::get('/meetings/{meeting}/tickets/create', 'MeetingController@ticketsCreate')->name('meetings.tickets.create');
    Route::get('/meetings/{meeting}/tickets/{ticket}', 'MeetingController@ticketShow')->name('meetings.tickets.show');
    Route::post('/meetings/{meeting}/tickets/{ticket}/task', 'MeetingController@ticketsCreateTask');
    Route::get('/meetings/{meeting}/tickets/{ticket}/download', 'MeetingController@ticketDownload');
    Route::get('/meetings/{meeting}/changeDate', 'MeetingController@changeDate');

    Route::get('/meetings/{meeting}/tickets/{ticket}/task/{task}/delete', 'MeetingController@ticketsDeleteTask');
    Route::get('/meetings/{meeting}/tickets/{ticket}/delete', 'MeetingController@ticketDelete');

    Route::get('meetings/{meeting}/exam/{examProtocol}/detachTicket', 'MeetingController@detachTicket');
    Route::get('meetings/{meeting}/exam/{examProtocol}/attachTicket', 'MeetingController@attachTicket');

    Route::get('meetings/{meeting}/startExam', 'MeetingController@startExam');
    Route::get('meetings/{meeting}/closeExam', 'MeetingController@closeExam');

    Route::get('/meetings/{meeting}/ticketsConfirm', 'MeetingController@ticketsConfirm')->name('meetings.ticketsConfirm');

    Route::get('/agreement', 'MeetingController@agreement')->name('agreement');
    Route::get('/agreement/{meeting}/show', 'MeetingController@agreementShow')->name('agreement.show');
    Route::get('/agreement/{meeting}/success', 'MeetingController@agreementSuccess');
    Route::get('/agreement/{meeting}/fail', 'MeetingController@agreementFail');

    Route::get('/exam/{hash}', 'MeetingController@getTicket');

    Route::get('/vote', 'MeetingController@vote')->name('vote');
    Route::get('/vote/{meeting}/{type}/{user}/{vote}', 'MeetingController@voteSend');





});

//});

resources/views/subdivisions/create.blade.php
@extends('layouts.app')
@section('breadcrumbs')
    {{ \Diglactic\Breadcrumbs\Breadcrumbs::render('subdivisions.create') }}
@endsection
@section('content')

    <div class="mt-4">
        <div class="content content-box">

            <div class="row mt-2 mb-2">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Создание нового подразделения</h2>
                    </div>
                </div>
            </div>
            <create-edit-sub></create-edit-sub>
        </div>
    </div>


@endsection

resources/views/subdivisions/edit.blade.php
@extends('layouts.app')
@section('breadcrumbs')
    {{ \Diglactic\Breadcrumbs\Breadcrumbs::render('subdivisions.edit', $subdivision) }}
@endsection
@section('content')

    <div class="mt-4">
        <div class="content content-box">

            <div class="row mt-2 mb-2">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Редактирование данных структурного подразделения</h2>
                    </div>
                </div>
            </div>

            <create-edit-sub
                    type="edit"
                    level="{{ json_encode($subdivision->getLevel()) }}"
                    data="{{ $subdivision->toJson() }}"
                    data_user="{{ json_encode([ 'value' => $subdivision->getHeadFullName(), 'id' => $subdivision->head_id, 'data' => $subdivision->head ]) }}"
                    data_parent="{{ $subdivision->parent()->exists() ? json_encode($subdivision->parent) : '{}'}}">
            </create-edit-sub>

        </div>
    </div>


@endsection

resources/views/subdivisions/index.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    {{ \Diglactic\Breadcrumbs\Breadcrumbs::render('subdivisions') }}
@endsection

@section('content')

    <div class="mb-3">
        <div class="content">
            <div class="dashboard">
                <div class="dashboard-cards">
                    <a class="dashboard-card grow-fix blue" href="{{ route('subdivisions.create') }}">
                        <p class="dashboard-card-title">
                            Создать подразделение
                        </p>
                        <p class="dashboard-card-icon">
                            <i class="bi bi-person-plus"></i>
                        </p>
                    </a>
                    <a class="dashboard-card grow-fix green" href="{{ route('groups.create') }}">
                        <p class="dashboard-card-title">
                            Добавить группу
                        </p>
                        <p class="dashboard-card-icon">
                            <i class="bi bi-journal-plus"></i>
                        </p>
                    </a>
                </div>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="mt-4">
        <div class="content content-box">

            <div class="row mt-2 mb-2">
                <div class="col-lg-12 margin-tb">
                    <div class="pull-left">
                        <h2>Список подразделений</h2>
                    </div>
                </div>
            </div>

            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center">№</th>
                        <th>Подразделение</th>
                        <th>Должность руководителя</th>
                        <th>Руководитель</th>
                        <th class="text-center"><i class="bi bi-gear-fill"></i></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($subdivisions as $key => $subdivision)
                        <tr valign="middle">
                            <td align="center">{{ $subdivisions->currentPage() * $subdivisions->perPage() - $subdivisions->perPage() + $loop->iteration }}</td>
                            <td>
                                <a href="/subdivisions/{{ $subdivision->id }}">{{ $subdivision->name }}</a>
                            </td>
                            <td>
                                {{ $subdivision->head_degree }}
                            </td>
                            <td>
                                <a href="/users/{{ $subdivision->head_id }}" target="_blank"> {{ $subdivision->getHeadFullName() }}</a>
                            </td>
                            <td align="center">

                                <b-dropdown right variant="outline-dark">
                                    <template #button-content>
                                        <i class="bi bi-gear-fill"></i>
                                    </template>

                                    @can('subdivision-edit')
                                        <b-dropdown-item href="/subdivisions/{{ $subdivision->id }}/edit">
                                            Редактировать данные
                                        </b-dropdown-item>
                                    @endcan

                                    @can('subdivision-delete')
                                        <b-dropdown-item>
                                            <confirm-link
                                                    class="dropdown-item p-0"
                                                    type_query="delete"
                                                    ok_title="Удалить"
                                                    ok_variant="danger"
                                                    title="Удаление подразделения"
                                                    text="Вы уверены, что хотите удалить подразделение '{{ $subdivision->name }}'"
                                                    redirect="/subdivisions"
                                                    href="/subdivisions/{{ $subdivision->id }}">
                                                Удалить
                                            </confirm-link>
                                        </b-dropdown-item>
                                    @endcan

                                </b-dropdown>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>

            <div>
                {{ $subdivisions->links() }}
            </div>

        </div>
    </div>
@endsection

resources/views/subdivisions/show.blade.php
@extends('layouts.app')

@section('breadcrumbs')
    {{ \Diglactic\Breadcrumbs\Breadcrumbs::render('subdivisions.show', $subdivision) }}
@endsection

@section('content')
    <div class="mt-4">
        <div class="content content-box">
            <div class="row mt-2 mb-2">
                <div class="col-lg-12 margin-tb">
                    <div>
                        <h2 class="mb-3">{{ $subdivision->name }}</h2>

                        @if($subdivision->parent()->exists())
                            <h4 class="text-right">Подразделение является частью подразделения:</h4>
                            <div class="text-right">
                                <a href="{{ route('subdivisions.show', $subdivision->parent) }}" class="meeting-item mb-3" style="">
                                        <h5 class="mb-1">{{ $subdivision->parent->name }}</h5>
                                    <p class="mb-0 d-flex meeting-item-text" style="justify-content: space-between;">
                                        <span class="pl-1 pr-1">{{ $subdivision->parent->head_degree }}</span>
                                        <span class="pl-1 pr-1">{{ $subdivision->parent->head->getFullName() }}</span>
                                    </p>
                                </a>
                            </div>
                        @endif

                        <h4 class="mb-0">{{ $subdivision->head_degree }}</h4>
                        <h4 class="mb-3">
                            <a href="/users/{{ $subdivision->head_id }}" target="_blank">{{ $subdivision->head->getFullName() }}</a>
                        </h4>

                        @if($subdivision->childs()->exists())
                           <div class="mb-3">
                               <h4>Структура подразделения:</h4>
                               @foreach($subdivision->childs as $child)
                                   <div class="ml-5">
                                       <a href="{{ route('subdivisions.show', $child) }}" class="meeting-item" style="width: 100%;">
                                           <h5 class="mb-1">{{ $child->name }}</h5>
                                           <p class="mb-0 meeting-item-text" style="">
                                               <span class="pl-1 pr-5">{{ $child->head_degree }}</span>
                                               <span class="pl-1 pr-1">{{ $child->head->getFullName() }}</span>
                                           </p>
                                       </a>
                                       @foreach($child->childs as $child2)
                                           <div class="ml-5">
                                               <a href="{{ route('subdivisions.show', $child2) }}" class="meeting-item" style="width: 100%;">
                                                   <h5 class="mb-1">{{ $child2->name }}</h5>
                                                   <p class="mb-0 meeting-item-text">
                                                       <span class="pl-1 pr-5">{{ $child2->head_degree }}</span>
                                                       <span class="pl-1 pr-1">{{ $child2->head->getFullName() }}</span>
                                                   </p>
                                               </a>
                                               @foreach($child2->childs as $child3)
                                                   <div class="ml-5">
                                                       <a href="{{ route('subdivisions.show', $child3) }}" class="meeting-item" style="width: 100%;">
                                                           <h5 class="mb-1">{{ $child3->name }}</h5>
                                                           <p class="mb-0 meeting-item-text">
                                                               <span class="pl-1 pr-5">{{ $child3->head_degree }}</span>
                                                               <span class="pl-1 pr-1">{{ $child3->head->getFullName() }}</span>
                                                           </p>
                                                       </a>
                                                       @foreach($child3->childs as $child4)
                                                           <div class="ml-5">
                                                               <a href="{{ route('subdivisions.show', $child4) }}" class="meeting-item" style="width: 100%;">
                                                                   <h5 class="mb-1">{{ $child4->name }}</h5>
                                                                   <p class="mb-0 meeting-item-text">
                                                                       <span class="pl-1 pr-5">{{ $child4->head_degree }}</span>
                                                                       <span class="pl-1 pr-1">{{ $child4->head->getFullName() }}</span>
                                                                   </p>
                                                               </a>
                                                           </div>
                                                       @endforeach
                                                   </div>
                                               @endforeach
                                           </div>
                                       @endforeach
                                   </div>
                               @endforeach
                           </div>
                        @endif
                        @if($subdivision->chair_groups()->count())
                            <div class="mb-3">
                                <h4>Список групп:</h4>
                                    <table class="table table-bordered table-hover">
                                        <thead>
                                        <tr>
                                            <th>Группа</th>
                                            <th>Студентов в группе</th>
                                            <th>Каферда</th>
                                            <th>Уровень образования</th>
                                            <th>Форма обучения</th>
                                            <th>Год выпуска</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        @foreach($subdivision->chair_groups as $key => $group)
                                            <tr valign="middle">
                                                <td>
                                                    <a href="/groups/{{ $group->id }}" target="_blank">{{ $group->name }}</a>
                                                </td>
                                                <td>
                                                    {{ $group->getCoutStudents() }}
                                                </td>
                                                <td>
                                                    {{ $group->getChairName() }}
                                                </td>
                                                <td>
                                                    {{ $group->getLevel() }}
                                                </td>
                                                <td>
                                                    {{ $group->getForm() }}
                                                </td>
                                                <td>
                                                    {{ $group->graduation_year }}
                                                </td>
                                            </tr>
                                        @endforeach
                                        </tbody>
                                    </table>
                            </div>
                        @endif

                        <div class="d-flex mt-5" style="justify-content: space-evenly;">
                            @can('subdivision-edit')
                                <a href="/subdivisions/{{ $subdivision->id }}/edit">Редактировать данные подразделения</a>
                            @endcan
                            @can('subdivision-delete')
                                <confirm-link
                                        class="text-danger"
                                        type_query="delete"
                                        ok_title="Удалить"
                                        ok_variant="danger"
                                        title="Удаление подразделения"
                                        text="Вы уверены, что хотите удалить подразделение '{{ $subdivision->name }}'"
                                        redirect="/subdivisions"
                                        href="/subdivisions/{{ $subdivision->id }}">
                                    Удалить подразделение
                                </confirm-link>
                            @endcan
                        </div>
                       {{-- <div class="row">
                            <div class="col-md-5">
                                <h3>Группа <a href="/groups/{{ $meeting->group_id }}" target="_blank">{{ $meeting->group_name }}</a></h3>
                                <p class="mb-0">Председатель комиссии:</p>
                                <p class="mb-1 indent-25">
                                    <a href="/user/{{ $meeting->getChairmanId() }}">{{ $meeting->getChairmanName('full') }}</a>
                                </p>
                                <p class="mb-0">Секретарь комиссии: </p>
                                <p class="mb-1 indent-25">
                                    <a href="/user/{{ $meeting->getSecretaryId() }}">{{ $meeting->getSecretaryName('full') }}</a>
                                </p>
                                <p class="mb-0">Члены комиссии: </p>
                                @foreach($meeting->persons as $person)
                                    <p class="mb-1 indent-25">
                                        <a href="/user/{{ $person->id }}">{{ $person->fullName }}</a>
                                    </p>
                                @endforeach
                            </div>
                            <div class="col-md-7">
                                @foreach(json_decode($meeting->sub) as $sub)
                                    @if(!empty($sub->id))
                                        <div class="mb-3">
                                            <p class="mb-1"><a href="/subdivisions/{{ $sub->id }}" target="_blank">{{ $sub->name }}</a></p>
                                            <p class="mb-0 d-flex" style="justify-content: space-between;">
                                                <span>{{ $sub->head_degree }}</span>
                                                <a target="_blank" href="/users/{{ $sub->head_id }}">{{ $sub->head_fio }}</a>
                                            </p>
                                        </div>
                                    @endif
                                @endforeach
                            </div>
                        </div>--}}
                    </div>
                   {{-- <div class="pull-left pl-2">
                        <div>
                            <h1 class="mb-0 d-inline-block">{{ $user->getFullName() }}</h1>
                            <h4 class="d-inline-block text-secondary">{{ empty($user->email) ? '' : '('.$user->email.')' }}</h4>
                        </div>
                        <p class="pl-3 text-right">
                            ({!! $user->getAuthStatusContent('icon') !!} - {{  $user->getAuthStatusContent('text') }})
                        </p>
                        <p>
                            Роли пользователя:<br>
                            @if($user->roles()->count() == 0)
                                <p class="text-secondary indent-25">У пользователя нет ролей в системе</p>
                            @endif
                            @foreach($user->roles()->get() as $role)
                                <label class="badge badge-success">{{ $role->title }}</label>
                            @endforeach
                        </p>
                        <div class="d-flex" style="justify-content: space-evenly;">
                            @can('user-edit')
                                <a href="/users/{{ $user->id }}/edit">Редактировать пользователя</a>
                            @endcan
                            @can('user-delete')
                                <confirm-link
                                    class="text-danger"
                                    type_query="delete"
                                    ok_title="Удалить"
                                    ok_variant="danger"
                                    title="Удаление пользователя"
                                    text="Вы уверены, что хотите удалить пользователя '{{ $user->getFullName() }}'"
                                    redirect="/users"
                                    href="/users/{{ $user->id }}">
                                    Удалить пользователя
                                </confirm-link>
                            @endcan
                        </div><hr>
                    </div>--}}
                </div>
            </div>
        </div>
    </div>
@endsection