routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\HomeController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\MeetingController;
use App\Http\Controllers\Auth\ResetPasswordController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    //return view('welcome');
    return redirect('/home');
});

// Роуты Laravel UI
Auth::routes();
// Редирект роута регистрации
Route::get('/register', function () {
    return redirect('/login');
});
// Предоставление доступа
Route::get('/password/fill/{token}', 'Auth\ResetPasswordController@fill')->name('password.fill');
Route::post('/password/fill/{token}', 'Auth\ResetPasswordController@fillPost')->name('password.fill.post');




Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');
Route::get('/certificate/{hash}', 'HomeController@certificate')->name('certificate');
Route::get('/centificate/{hash}', function ($hash) {
    return redirect('/certificate/'.$hash);
});

Route::group(['middleware' => ['auth']], function() {
    // API
    include('webapi.php');
    
    Route::resource('roles', 'RoleController');
    Route::resource('users', 'UserController', [ 'names' => 'users' ])->middleware('permission:user-edit');;
    Route::get('/users/{user}/auth', 'UserController@auth');

    Route::resource('meetings', 'MeetingController');
    Route::resource('subdivisions', 'SubdividionController');
    Route::resource('groups', 'GroupController');

    // Отвязывание роли
    Route::delete('users/{user}/detachRole/{role}', 'UserController@detachRole')->where('user', '[0-9]+')->where('role', '[0-9]+');
    // Привязка роли
    Route::post('users/{user}/attachRole/{role}', 'UserController@attachRole')->where('user', '[0-9]+')->where('role', '[0-9]+');

    // Настройки
    Route::get('/profile', 'UserController@profile')->name('profile');

    Route::get('/meetings/{meeting}/students', 'MeetingController@students')->name('meetings.students');
    Route::post('/meetings/{meeting}/students', 'MeetingController@postStudents')->middleware('permission:meeting-create');

    Route::get('/meetings/{meeting}/report/{user}', 'MeetingController@report')->name('meetings.report');
    Route::post('/meetings/{meeting}/report/{user}', 'MeetingController@postReport');
    Route::get('/meetings/{meeting}/report/{user}/download', 'MeetingController@downloadReport');

    Route::get('/meetings/{meeting}/exam/{user}', 'MeetingController@exam')->name('meetings.exam');
    Route::post('/meetings/{meeting}/exam/{user}', 'MeetingController@postExam');
    Route::get('/meetings/{meeting}/exam/{user}/download', 'MeetingController@downloadExam');

    Route::get('/meetings/{meeting}/exam/{examProtocol}/votes', 'MeetingController@examVotes');
    Route::get('/meetings/{meeting}/report/{reportProtocol}/votes', 'MeetingController@reportVotes');

    Route::get('/meetings/{meeting}/solution/{user}', 'MeetingController@solution')->name('meetings.solution');
    Route::post('/meetings/{meeting}/solution/{user}', 'MeetingController@postSolution');
    Route::get('/meetings/{meeting}/solution/{user}/download', 'MeetingController@downloadSolution');

    Route::get('/meetings/{meeting}/confirm', 'MeetingController@confirm')->name('meetings.confirm');

    Route::get('/meetings/{meeting}/tickets', 'MeetingController@tickets')->name('meetings.tickets');
    Route::get('/meetings/{meeting}/tickets/create', 'MeetingController@ticketsCreate')->name('meetings.tickets.create');
    Route::get('/meetings/{meeting}/tickets/{ticket}', 'MeetingController@ticketShow')->name('meetings.tickets.show');
    Route::post('/meetings/{meeting}/tickets/{ticket}/task', 'MeetingController@ticketsCreateTask');
    Route::get('/meetings/{meeting}/tickets/{ticket}/download', 'MeetingController@ticketDownload');
    Route::get('/meetings/{meeting}/changeDate', 'MeetingController@changeDate');

    Route::get('/meetings/{meeting}/tickets/{ticket}/task/{task}/delete', 'MeetingController@ticketsDeleteTask');
    Route::get('/meetings/{meeting}/tickets/{ticket}/delete', 'MeetingController@ticketDelete');

    Route::get('meetings/{meeting}/exam/{examProtocol}/detachTicket', 'MeetingController@detachTicket');
    Route::get('meetings/{meeting}/exam/{examProtocol}/attachTicket', 'MeetingController@attachTicket');

    Route::get('meetings/{meeting}/startExam', 'MeetingController@startExam');
    Route::get('meetings/{meeting}/closeExam', 'MeetingController@closeExam');

    Route::get('/meetings/{meeting}/ticketsConfirm', 'MeetingController@ticketsConfirm')->name('meetings.ticketsConfirm');

    Route::get('/agreement', 'MeetingController@agreement')->name('agreement');
    Route::get('/agreement/{meeting}/show', 'MeetingController@agreementShow')->name('agreement.show');
    Route::get('/agreement/{meeting}/success', 'MeetingController@agreementSuccess');
    Route::get('/agreement/{meeting}/fail', 'MeetingController@agreementFail');

    Route::get('/exam/{hash}', 'MeetingController@getTicket');

    Route::get('/vote', 'MeetingController@vote')->name('vote');
    Route::get('/vote/{meeting}/{type}/{user}/{vote}', 'MeetingController@voteSend');





});

//});

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

@include('layouts.head')

<body>
    <div id="app">
        @include('layouts.header')

        <main>
            @yield('content')
        </main>
        <footer class="footer">
            <p>ВКР студента группы 18-ИСТв-1 Попова Алексея Юрьевича <br> НГТУ им. Р.Е. Алексеева <br> 2022 г.</p>
        </footer>
        {{--
        TODO:: НА СЛУЧАЙ ЕСЛИ НАДО БУДЕТ ПОДТВЕРДИТЬ ПРАВО НА ИСПОЛЬЗОВАНИЕ КАРТИНОК
        <div style="display: none;">
            Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from
            <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
        </div>--}}
    </div>
</body>
</html>

resources/views/layouts/breadcrumbs.blade.php
@unless ($breadcrumbs->isEmpty())
    <nav class="navbar navbar-light mt-2 pb-0" aria-label="breadcrumb">

            <ol class="breadcrumb content p-0 bg-light">
                @foreach ($breadcrumbs as $breadcrumb)

                    @if ($breadcrumb->url && !$loop->last)
                        <li class="breadcrumb-item"><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
                    @else
                        <li class="breadcrumb-item active">{{ $breadcrumb->title }}</li>
                    @endif

                @endforeach
            </ol>

    </nav>
@endunless

resources/views/layouts/head.blade.php
@once
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <!-- Yandex -->
        <meta name="yandex-verification" content="{{ config('app.yandex-verification', '') }}" />

        <title>{{ config('app.name', 'Заседания ГЭК') }}</title>

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
        <script src="{{ asset('js/jquery-1.11.2.min.js') }}"></script>
        <script src="{{ asset('js/jquery.cecutient.js') }}"></script>
        <script src="{{ asset('js/name.js') }}"></script>

        <!-- Fonts -->
    {{--<link rel="dns-prefetch" href="//fonts.gstatic.com">--}}
    {{--<link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">--}}

    <!-- Styles -->
        <link href="{{ asset('css/app.css') }}" rel="stylesheet">
        <link href="{{ asset('css/jquery.cecutient.css') }}" rel="stylesheet">

        <script type="text/javascript">
            jQuery(function($) {
                $('#cecutient').cecutient({
                    increment: 1,
                    target: "#app main",
                    imageClass: ".cecutientImagesOn",
                    minimumFontSize : 0,
                    maximumFontSize : 10,
                    skipForFont: ".skip",
                    container: "#panelWrapper",
                    containerPath: "/templates",
                    language: 'en'
                });
            });
        </script>
    </head>
@endonce

resources/views/layouts/header.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white bg-white-please shadow-sm">
    <div class="container">
        {{-- Название + кнопка --}}
        <a class="navbar-brand" href="{{ url('/home') }}">
            {{--<i class="bi bi-mortarboard fs-32 pr-2"></i>--}}
            <img src="/img/mortarboard_4.png" height="64px" alt="">
            {{ config('app.name', 'Заседания ГЭК') }}
        </a>
        <button class="navbar-toggler fs-16" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Навигационная панель') }}">
            <i class="bi bi-list"></i>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <li><a class="nav-link" id="cecutient" href="#"></a></li>
                <!-- Authentication Links -->
                @guest
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('login') }}">Войти</a>
                </li>
                @else
                    {{--<li><a class="nav-link" href="{{ route('users.index') }}">Manage Users</a></li>--}}
                    {{--<li><a class="nav-link" href="{{ route('roles.index') }}">Manage Role</a></li>--}}
                    {{--<li><a class="nav-link" href="{{ route('meetings.index') }}">Manage Meeting</a></li>--}}
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->getFullName() }}
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            <a class="dropdown-item" href="{{ route('profile') }}">
                                Профиль
                            </a>

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">
                                Выйти
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        </div>
                    </li>
                    @endguest
            </ul>
        </div>
    </div>
</nav>
<div id="panelWrapper"></div>

@yield('breadcrumbs')